LalraenMainAzureWeb/Controllers/EdrpouParserController.cs
using LalraenMainAzureWeb.Models;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using AngleSharp;
using AngleSharp.Html;
using AngleSharp.Html.Parser;

namespace LalraenMainAzureWeb.Controllers
{
    public class EdrpouParserController : Controller
    {
        // GET: EdrpouParser
        [HttpGet]
        public ActionResult EdrpouParser()
        {            
            return View();
        }

        [HttpPost]
        public ActionResult EdrpouParser(OrganisationModel organisationModel)
        {
            OrganisationModel organisationModelData = Parser(organisationModel, organisationModel.EdrpouCode);
            return View(organisationModelData);
        }

        /// <summary>
        /// Gives OrganisationModel info
        /// </summary>
        /// <param name="edrpou"></param>
        /// <returns></returns>
        public static OrganisationModel Parser(OrganisationModel organisationModel, string edrpou)
        {
            if (edrpou.Length == 8)
                return EdrpouDetailParser(organisationModel);
            else if (edrpou.Length == 10)
                return FopDataParser(organisationModel);
            else
                return null;
        }

        /// <summary>
        /// Gets data from open API edr.data-gov-ua.org/api
        /// </summary>
        /// <param name="edrpou">Input EDRPOU code to get info about</param>
        /// <returns>String with basic info like: FullName, Occupation and Status.</returns>
        private static OrganisationModel EdrpouDetailParser(OrganisationModel organisationModel)
        {
            var edrpou = organisationModel.EdrpouCode;
            using (WebClient client = new WebClient())
            {
                client.Encoding = Encoding.UTF8;
                string linkEdrpou = "http://edr.data-gov-ua.org/api/companies?where={\"edrpou\":{\"contains\":\"" + edrpou + "\"}}";
                string pageEdrpou = client.DownloadString(linkEdrpou);

                Regex regexOrgInfo = new Regex(
                @"officialName"":(?<ofName>.+)"",""address""
                | address"":(?<address>.+)"",""mainPerson""
                | mainPerson"":(?<mainPerson>.+)"",""occupation""
                | occupation"":(?<occupation>.+)"",""status""
                | status"":(?<status>.+)"",""id""
                ");
                Match matchInfo = regexOrgInfo.Match(pageEdrpou);
                organisationModel.OfficialName = matchInfo.Groups["ofName"].Value.ToString();
                organisationModel.Address = matchInfo.Groups["address"].Value.ToString();
                organisationModel.MainPerson = matchInfo.Groups["mainPerson"].Value.ToString();
                organisationModel.Occupation = matchInfo.Groups["occupation"].Value.ToString();
                organisationModel.Status = matchInfo.Groups["status"].Value.ToString();
            }
            return organisationModel;
        }

        /// <summary>
        /// Gets data about FOP from youcontrol. Be carefull. NOT SO FAST. DO SLEEP
        /// </summary>
        /// <param name="inn">INN code</param>
        /// <returns>OrganisationModel</returns>
        private static OrganisationModel FopDataParser(OrganisationModel organisationModel)
        {
            var inn = organisationModel.EdrpouCode;
            string link = "https://youcontrol.com.ua/search/?country=1&q=" + inn;
            using (WebClient client = new WebClient())
            {
                client.Encoding = Encoding.UTF8;
                string page = client.DownloadString(link);
                //Regex regex = new Regex(" <meta name=\"description\" content=\" (?<result>.+) Повне досьє на");
                Regex regex = new Regex("Повне досьє на (?<result>.+) ,");
                Match match = regex.Match(page);
                organisationModel.MainPerson = match.Groups["result"].Value.ToString();
            }
            return organisationModel;
        }
    
        private static OrganisationModel EdrpouDetailParser2(OrganisationModel organisationModel)
        {

            var edrpou = organisationModel.EdrpouCode;
            string linkEdrpou = "http://edr.data-gov-ua.org/api/companies?where={\"edrpou\":{\"contains\":\"" + edrpou + "\"}}";
            var parser = new HtmlParser();
            var doc = parser.ParseDocument(linkEdrpou);
            
            return organisationModel;
        }
    }
}

LalraenMainAzureWeb/Controllers/HomeController.cs
using System;
using System.Web;
using System.Web.Mvc;

namespace LalraenMainAzureWeb.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Main()
        {
            var cookie = new HttpCookie("testCookie", DateTime.Now.ToString("dd.MM.yyyy"));
            Response.SetCookie(cookie);
            return View();
        }

        public RedirectResult RedirectDonate()
        {
            return Redirect("https://send.monobank.ua/45CJRjVgEC");
        }

        public RedirectResult RedirectGitHub()
        {
            return Redirect("https://github.com/lalraenod");
        }
    }
}

LalraenMainAzureWeb/Views/Home/ElectricityMain.cshtml
@model LalraenMainAzureWeb.Models.MeterModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Electricity payment calculation</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
</head>
<body>
    <h1 class="text-center"><strong>Calculate your electricity payment here</strong></h1>
    @using (Html.BeginForm("Calculate", "ElectricityPayment", FormMethod.Post))
    {
        <div class="text-lg-center mt-lg-5">
            <label for="LastReadings">Enter last meter readings:</label>
            <input class="text-center" id="LastReadings" type="text" placeholder="1000" size="5" />
        </div>
        <div class="text-lg-center">
            <label for="CurrentReadings">Enter current meter readings:</label>
            <input class="text-center" id="CurrentReadings" type="text" placeholder="1200" size="5" />
        </div>
    }
    <div class="text-lg-center mt-3">
        <button class="btn btn-success btn-lg">Calculate</button>
    </div>
    <div id="sumToPay" class="text-lg-center invisible">
        <label for="Sum to pay"></label>
        <p>Sum in UAH to pay: <output name="sumToPay"></output></p>
    </div>
    <div class="text-lg-center fixed-bottom">
        <button class="btn btn-danger btn-lg mb-lg-5">
            @Html.ActionLink("Main", "Main", "Home")
        </button>
    </div>
</body>
</html>

LalraenMainAzureWeb/Views/Home/Index.cshtml
@model LalraenMainAzureWeb.Models.UserModel

@{
    ViewBag.Title = "Lalraen Home Page";
    Layout = "";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <style>
        .form-control {
            width: auto;
            margin: auto;
            text-align: center;
        }
        .label{
            width:auto;
            text-align:center;
            margin:auto;
        }
    </style>
</head>
<body>
    <div class="text-center mb-4">
        <h1>
            <strong>Lalraen Home Page Welcomes You!</strong>
        </h1>
    </div>
    <div>
        <table class="m-auto">
            <tr>
                <td class="mr-lg-5">
                    <div class="text-center m-lg-5">
                        <h1>Login Form</h1>
                    </div>
                    <div class="mt-3">
                        @Html.LabelFor(m => m.Email,
                       new { @class = "label" })
                        @Html.TextBoxFor(m => m.Email,
                       new { @class = "form-control" })
                    </div>
                    <div class="mt-3">
                        @Html.LabelFor(m => m.Password,
                       new { @class = "label" })
                        @Html.PasswordFor(m => m.Password,
                       new { @class = "form-control" })
                    </div>
                    <div class="text-center">
                        <button class="btn btn-primary btn-lg mt-lg-5" type="button">
                            @Html.ActionLink("Login", "Main")
                        </button>
                    </div>
                </td>
                <td>
                    <div class="text-center m-lg-5">
                        <h1>SignUp Form</h1>
                    </div>
                    <div class="mt-3">
                        @Html.LabelFor(m => m.Email,
                       new { @class = "label" })
                        @Html.TextBoxFor(m => m.Email,
                       new { @class = "form-control" })
                    </div>
                    <div class="mt-3">
                        @Html.LabelFor(m => m.Password,
                       new { @class = "label" })                        
                        @Html.PasswordFor(m => m.Password,
                       new { @class = "form-control" })
                    </div>
                    <div class="text-center">                        
                        <button class="btn btn-primary btn-lg mt-5" type="button">
                            @Html.ActionLink("SignUp", "Main")
                        </button>
                    </div>
                </td>
            </tr>
        </table>
    </div>
    <div class="text-center mt-lg-5">
        <button class="btn btn-info btn-lg">
            @Html.ActionLink("Home", "Main")
        </button>
    </div>
</body>
</html>

LalraenMainAzureWeb/Views/Home/LoginForm.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LoginForm</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
</head>
<body>
    <div class="text-center m-lg-5">
        <h1>NOT YET IMPLEMENTED</h1>
    </div>
    <div class="text-center">
        <button class="btn btn-primary btn-lg" type="button">
            @Html.ActionLink("Main", "Main")
        </button>
    </div>
</body>
</html>

LalraenMainAzureWeb/Views/Home/Main.cshtml
@{
    ViewBag.Title = "Lalraen main programs";
    Layout = "~/Views/_LayoutPage.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Main page</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <h1 class="text-center mt-3"><strong>Lalraen main programs</strong></h1>
    <div class="text-lg-center mt-3">
        <button class="btn btn-primary btn-lg">
            <img src="" />
            @Html.ActionLink("Monobank", "Monobank", "Monobank")
        </button>
        <button class="btn btn-primary btn-lg">
            @Html.ActionLink("Electricity", "Electricity", "Electricity")
        </button>
        <button class="btn btn-secondary btn-lg">
            @Html.ActionLink("EdrpouParser(WIP)", "EdrpouParser", "EdrpouParser")
        </button>
    </div>
    <div class="text-lg-center mt-3">
        <button class="btn btn-secondary btn-lg">
            @Html.ActionLink("PC's info (NYI)", "PcInfo")
        </button>
        <button class="btn btn-primary btn-lg">
            @Html.ActionLink("GitHub", "RedirectGitHub")
        </button>
    </div>
    <div class="text-lg-center mt-3">
        <button class="btn btn-secondary btn-lg">
            @Html.ActionLink("MoneyControl(NYI)", "Main")
        </button>
        <button class="btn btn-secondary btn-lg">
            @Html.ActionLink("Shopping List(NYI)", "Main")
        </button>
    </div>
</body>
</html>

LalraenMainAzureWeb/Views/Home/MonobankMain.cshtml
@model LalraenMainAzureWeb.Models.InstallmentModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Monobank installment calculation</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <h1 class="text-center"><strong>Calculate your Monobank installment payment here</strong></h1>
    <div class="text-lg-center mt-lg-5">
        <label for="InstallmentSum">Enter summary of your installment:</label>
        <input class="text-center" id="InstallmentSum" type="text" placeholder="1000" size="5" />
    </div>
    <div class="text-lg-center">
        <label for="InstallmentDuration">Select installment duration (from 3 to 24 months):</label>
        <input class="text-center" id="InstallmentDuration" type="text" placeholder="3" size="5" />
    </div>
    <div class="text-lg-center">
        <label for="InstallmentPercent">InstallmentPercent:</label>
        <input class="text-center" id="InstallmentPercent" type="text" value="1,9" size="5" /> %
    </div>
    <div class="text-lg-center mt-3">
        <button class="btn btn-success btn-lg">Calculate</button>
    </div>
    <div id="installSumPerMonth" class="text-lg-center invisible">
        <label for="installSumPerMonth"></label>
        <p>Sum to pay each month: <output name="InstallSumPerMonth"></output></p>
    </div>
    <div id="installFinalSum" class="text-lg-center invisible">
        <label for="installFinalSum"></label>
        <p>All sum to pay: <output name="InstallFinalSum"></output></p>
    </div>
    <div id="installOverPayment" class="text-lg-center invisible">
        <label for="installOverPayment"></label>
        <p>Overpayment: <output name="InstallOverPayment"></output></p>
    </div>
    <div class="text-lg-center fixed-bottom">
        <button class="btn btn-danger btn-lg mb-lg-5">
            @Html.ActionLink("Main", "Main", "Home")
        </button>
    </div>
</body>
</html>

LalraenMainAzureWeb/Views/Home/SignupForm.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SignupForm</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div class="text-center m-lg-5">
        <h1>NOT YET IMPLEMENTED</h1>
    </div>
    <div class="text-center">
        <button class="btn btn-primary btn-lg" type="button">
            @Html.ActionLink("Main", "Main")
        </button>
    </div>
</body>
</html>